### ISSUE TITLE
compile.sh fails

### ISSUE THREAD

**Issue by skandragon** [samwize/wwdc-dl#1]
`SilverGryphon:wwdc-dl explorer$ sh compile.sh
wwdc-dl-tmp.swift:1:3: error: consecutive statements on a line must be separated by ';'
-e #!/usr/bin/swift
  ^
  ;
wwdc-dl-tmp.swift:1:4: error: expected expression
-e #!/usr/bin/swift
   ^
wwdc-dl-tmp.swift:1:2: error: use of unresolved identifier 'e'
-e #!/usr/bin/swift
 ^`

I changed the file to be:

``` #!/bin/bash

rm -f wwdc-dl-tmp.swift
echo "#!/usr/bin/swift" > wwdc-dl-tmp.swift
echo "" >> wwdc-dl-tmp.swift
cat wwdc-dl-Playground.playground/Contents.swift >> wwdc-dl-tmp.swift
xcrun -sdk macosx swiftc wwdc-dl-tmp.swift -o wwdc-dl
```

**Comment by samwize** [comment]
Thanks for the suggestion. The `-e` in `echo` might not work on some shell, so it's safer to remove as you suggested.
